export type ThemePalette = {
  background: string;
  surface: string;
  card: string;
  border: string;
  accent: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  textAccent: string;
  textAccentMuted: string;
  textWhite: string;
  inputBackground: string;
  inputPlaceholder: string;
  iconAccent: string;
  iconMuted: string;
  iconDanger: string;
  iconSuccess: string;
  iconWarning: string;
  iconTip: string;
  buttonPrimary: string;
  buttonSecondary: string;
  buttonSecondaryBorder: string;
  statusSuccessBg: string;
  statusSuccessText: string;
  statusWarningBg: string;
  statusWarningText: string;
  statusDangerBg: string;
  statusDangerText: string;
  statusInfoBg: string;
  statusInfoText: string;
  statusGrayBg: string;
  statusGrayText: string;
  switchTrackOff: string;
  switchTrackOn: string;
  switchThumb: string;
  tipBackground: string;
  tipBorder: string;
  tipHeading: string;
  tipBody: string;
  tipLink: string;
  vibeActiveBg: string;
  vibeActiveBorder: string;
  vibeInactiveBg: string;
  vibeInactiveBorder: string;
  vibeInactiveText: string;
  modalBackground: string;
};

export function getThemePalette(theme?: string): ThemePalette {
  const isDark = theme === "dark";

  if (isDark) {
    return {
      background: "bg-dark-background",
      surface: "bg-dark-surface",
      card: "bg-dark-card",
      border: "border-dark-border",
      accent: "bg-dark-accent",
      textPrimary: "text-dark-text-primary",
      textSecondary: "text-dark-text-secondary",
      textMuted: "text-dark-text-muted",
      textAccent: "text-dark-text-accent",
      textAccentMuted: "text-dark-text-accentMuted",
      textWhite: "text-dark-text-white",
      inputBackground: "bg-dark-input-background",
      inputPlaceholder: "placeholder:text-dark-input-placeholder",
      iconAccent: "#60a5fa",
      iconMuted: "#94a3b8",
      iconDanger: "#f87171",
      iconSuccess: "#22c55e",
      iconWarning: "#f59e0b",
      iconTip: "#93c5fd",
      buttonPrimary: "bg-dark-button-primary",
      buttonSecondary: "bg-dark-button-secondary",
      buttonSecondaryBorder: "border-dark-button-secondaryBorder",
      statusSuccessBg: "bg-dark-status-success-bg",
      statusSuccessText: "#22c55e",
      statusWarningBg: "bg-dark-status-warning-bg",
      statusWarningText: "#f59e0b",
      statusDangerBg: "bg-dark-status-danger-bg",
      statusDangerText: "#f87171",
      statusInfoBg: "bg-dark-status-info-bg",
      statusInfoText: "#60a5fa",
      statusGrayBg: "bg-dark-status-gray-bg",
      statusGrayText: "#9ca3af",
      switchTrackOff: "#1f2937",
      switchTrackOn: "#2563eb",
      switchThumb: "#f1f5f9",
      tipBackground: "bg-dark-tip-background",
      tipBorder: "border-dark-tip-border",
      tipHeading: "text-dark-tip-heading",
      tipBody: "text-dark-tip-body",
      tipLink: "text-dark-tip-link",
      vibeActiveBg: "bg-dark-vibe-active-bg",
      vibeActiveBorder: "border-dark-vibe-active-border",
      vibeInactiveBg: "bg-dark-vibe-inactive-bg",
      vibeInactiveBorder: "border-dark-vibe-inactive-border",
      vibeInactiveText: "text-dark-text-secondary",
      modalBackground: "bg-dark-modal-background",
    };
  }

  return {
    background: "bg-light-background",
    surface: "bg-light-surface",
    card: "bg-light-card",
    border: "border-light-border",
    accent: "bg-light-accent",
    textPrimary: "text-light-text-primary",
    textSecondary: "text-light-text-secondary",
    textMuted: "text-light-text-muted",
    textAccent: "text-light-text-accent",
    textAccentMuted: "text-light-text-accentMuted",
    textWhite: "text-light-text-white",
    inputBackground: "bg-light-input-background",
    inputPlaceholder: "placeholder:text-light-input-placeholder",
    iconAccent: "#2563eb",
    iconMuted: "#475569",
    iconDanger: "#dc2626",
    iconSuccess: "#22c55e",
    iconWarning: "#f59e0b",
    iconTip: "#bfdbfe",
    buttonPrimary: "bg-light-button-primary",
    buttonSecondary: "bg-light-button-secondary",
    buttonSecondaryBorder: "border-light-button-secondaryBorder",
    statusSuccessBg: "bg-light-status-success-bg",
    statusSuccessText: "#22c55e",
    statusWarningBg: "bg-light-status-warning-bg",
    statusWarningText: "#f59e0b",
    statusDangerBg: "bg-light-status-danger-bg",
    statusDangerText: "#dc2626",
    statusInfoBg: "bg-light-status-info-bg",
    statusInfoText: "#2563eb",
    statusGrayBg: "bg-light-status-gray-bg",
    statusGrayText: "#6b7280",
    switchTrackOff: "#cbd5f5",
    switchTrackOn: "#2563eb",
    switchThumb: "#f8fafc",
    tipBackground: "bg-light-tip-background",
    tipBorder: "border-light-tip-border",
    tipHeading: "text-light-tip-heading",
    tipBody: "text-light-tip-body",
    tipLink: "text-light-tip-link",
    vibeActiveBg: "bg-light-vibe-active-bg",
    vibeActiveBorder: "border-light-vibe-active-border",
    vibeInactiveBg: "bg-light-vibe-inactive-bg",
    vibeInactiveBorder: "border-light-vibe-inactive-border",
    vibeInactiveText: "text-light-text-secondary",
    modalBackground: "bg-light-modal-background",
  };
}